echo ""
echo -e "${CLR_RESET}"
echo -e "${CLR_YELLOW}EEEEEEEEEEEEEEEEEE EEEEEEEEEEEEEEEEEEE"
echo -e "${CLR_YELLOW}EEEEEEEEEEEEEEEEE   EEEEEEEEEEEEEEEEEE"
echo -e "${CLR_YELLOW}EEEE                              EEEE    ${CLR_RESET}Seeds Creative Services WordPress Installer"
echo -e "${CLR_YELLOW}EEEE                              EEEE    ${CLR_RESET}Made by Sebastian Inman ${CLR_CYAN}sebastian@seedscs.com"
echo -e "${CLR_YELLOW}EEEEEEEEEEEE              EEEEEEEEEEEE"
echo -e "${CLR_YELLOW}EEEEEEEEEEEE              EEEEEEEEEEEE    ${CLR_RESET}This script automatically installs and configures"
echo -e "${CLR_YELLOW}EEEE                              EEEE    ${CLR_RESET}a fast and secure Nginx web server with the latest"
echo -e "${CLR_YELLOW}EEEE                              EEEE    ${CLR_RESET}build of WordPress."
echo -e "${CLR_YELLOW}EEEEEEEEEEEEEEEEE   EEEEEEEEEEEEEEEEEE"
echo -e "${CLR_YELLOW}EEEEEEEEEEEEEEEEEE EEEEEEEEEEEEEEEEEEE"
echo -e "${CLR_RESET}"
echo ""
echo ""
